"""
Structured vocabulary-card generation helpers.

Gemini can enrich each detected item, but this module keeps validation and
fallback deterministic so every detected vocabulary item still appears.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from typing import Any, Dict, Iterable, List

from content_intelligence import VocabularyItem


CORE_TRANSLATION_LEXICON = {
    "açmak": "to open",
    "anneler günü": "Mother's Day",
    "arkadaş": "friend",
    "çocuk odası": "children's room",
    "elma": "apple",
    "gelmek": "to come",
    "gitmek": "to go",
    "hata yapmak": "to make a mistake",
    "kapı": "door",
    "kapatmak": "to close",
    "kitap": "book",
    "mavi": "blue",
    "okumak": "to read",
    "yazmak": "to write",
}


@dataclass(frozen=True)
class VocabularyCard:
    turkish: str
    item_type: str
    translation: str
    cefr_level: str
    example_tr: str
    example_translation: str
    learner_note: str
    tts_word: str
    tts_sentence: str


def build_translation_lexicon(knowledge: Iterable[Dict[str, Any]]) -> Dict[str, str]:
    """Build a small deterministic Turkish->English lexicon from curated vocab."""
    lexicon: Dict[str, str] = {}
    for entry in knowledge:
        if entry.get("category") != "vocabulary":
            continue
        for line in str(entry.get("content", "")).splitlines():
            if " = " not in line:
                continue
            turkish, english = line.split(" = ", 1)
            for variant in re.split(r"\s*/\s*", turkish.strip()):
                if variant:
                    lexicon[variant.casefold()] = english.strip()
    return lexicon


def build_vocabulary_json_prompt(
    items: List[VocabularyItem],
    target_language: str,
    cefr_level: str,
) -> str:
    numbered = "\n".join(
        f"{index + 1}. {item.text} [{item.item_type}]"
        for index, item in enumerate(items)
    )
    return f"""You are a Turkish vocabulary tutor.

Create one vocabulary card for EVERY item below, in the exact same order.
The learner's CEFR Turkish level is {cefr_level}.
The target explanation language is {target_language}.

Vocabulary items:
{numbered}

Return ONLY valid JSON. Do not use Markdown fences.
Use this exact shape:
{{
  "cards": [
    {{
      "turkish": "original Turkish item",
      "item_type": "noun|verb|adjective/color|nationality|place/country|phrase|unknown",
      "translation": "{target_language} translation of the item",
      "cefr_level": "{cefr_level}",
      "example_tr": "short Turkish phrase or sentence using the item, level-appropriate",
      "example_translation": "{target_language} translation of example_tr",
      "learner_note": "one short useful note",
      "tts_word": "text to speak for the word",
      "tts_sentence": "text to speak for the example"
    }}
  ]
}}

Rules:
- Include all {len(items)} items exactly once.
- Keep A1/A2 examples short and concrete.
- For verbs, use natural forms, not only dictionary infinitives.
- Preserve Turkish characters.
- If an OCR item looks misspelled, keep the original in "turkish" and mention the likely correction in learner_note."""


def _extract_json_object(raw: str) -> Dict[str, Any]:
    text = raw.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end == -1 or end <= start:
        raise ValueError("No JSON object found in model response.")
    return json.loads(text[start:end + 1])


def fallback_card(
    item: VocabularyItem,
    target_language: str,
    cefr_level: str,
    lexicon: Dict[str, str] | None = None,
) -> VocabularyCard:
    translation = (lexicon or {}).get(item.text.casefold(), "") or CORE_TRANSLATION_LEXICON.get(item.text.casefold(), "")
    if not translation:
        translation = "Needs translation" if target_language.lower() == "english" else f"Needs {target_language} translation"

    if item.item_type == "verb":
        example_tr = f"{item.text} istiyorum."
        example_translation = f"I want to {translation.lower().replace('to ', '', 1)}."
    elif item.item_type == "adjective/color":
        example_tr = f"Bu {item.text}."
        example_translation = f"This is {translation.lower()}."
    else:
        example_tr = f"Bu {item.text}."
        article = "an" if translation[:1].lower() in {"a", "e", "i", "o", "u"} else "a"
        example_translation = f"This is {article} {translation.lower()}."

    return VocabularyCard(
        turkish=item.text,
        item_type=item.item_type,
        translation=translation,
        cefr_level=cefr_level,
        example_tr=example_tr,
        example_translation=example_translation,
        learner_note="Generated by deterministic fallback; review if this came from noisy OCR.",
        tts_word=item.text,
        tts_sentence=example_tr,
    )


def _coerce_card(
    raw_card: Dict[str, Any],
    item: VocabularyItem,
    target_language: str,
    cefr_level: str,
    lexicon: Dict[str, str],
) -> VocabularyCard:
    fallback = fallback_card(item, target_language, cefr_level, lexicon)

    def clean(value: Any, default: str) -> str:
        text = str(value or "").strip()
        return text if text else default

    return VocabularyCard(
        turkish=item.text,
        item_type=clean(raw_card.get("item_type"), item.item_type),
        translation=clean(raw_card.get("translation"), fallback.translation),
        cefr_level=clean(raw_card.get("cefr_level"), cefr_level),
        example_tr=clean(raw_card.get("example_tr"), fallback.example_tr),
        example_translation=clean(raw_card.get("example_translation"), fallback.example_translation),
        learner_note=clean(raw_card.get("learner_note"), fallback.learner_note),
        tts_word=clean(raw_card.get("tts_word"), item.text),
        tts_sentence=clean(raw_card.get("tts_sentence"), fallback.example_tr),
    )


def parse_vocabulary_cards(
    raw_response: str,
    items: List[VocabularyItem],
    target_language: str,
    cefr_level: str,
    lexicon: Dict[str, str] | None = None,
) -> tuple[List[VocabularyCard], str]:
    """Parse model JSON, preserving all items with fallbacks if needed."""
    lexicon = lexicon or {}
    try:
        data = _extract_json_object(raw_response)
        raw_cards = data.get("cards", [])
        if not isinstance(raw_cards, list):
            raise ValueError("JSON field 'cards' is not a list.")
    except (json.JSONDecodeError, ValueError, TypeError) as exc:
        return (
            [fallback_card(item, target_language, cefr_level, lexicon) for item in items],
            f"Vocabulary JSON could not be parsed; deterministic fallback used. {exc}",
        )

    cards = []
    for index, item in enumerate(items):
        raw_card = raw_cards[index] if index < len(raw_cards) and isinstance(raw_cards[index], dict) else {}
        cards.append(_coerce_card(raw_card, item, target_language, cefr_level, lexicon))

    warning = ""
    if len(raw_cards) != len(items):
        warning = (
            f"Model returned {len(raw_cards)} cards for {len(items)} items; "
            "missing or extra cards were repaired deterministically."
        )
    return cards, warning
